const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fetch(window.portfolioLanguage==='mn'?'/data/portfolio.mn.json':'/data/portfolio.json').then(r => {if(!r.ok) throw new Error('Content unavailable'); return r.json()}).then(data => {
 const e=escapeHTML;
 const email=document.querySelector("#email");if(email){email.href="mailto:"+data.contact.email;email.textContent=data.contact.email+" ↗";}
 const location=document.querySelector("#location");if(location)location.textContent=data.contact.location;
 const projects=document.querySelector('#projects');
 if(projects) projects.innerHTML=data.projects.map((p,i)=>`<article class="project reveal" data-slug="${e(p.slug)}" id="project-${e(p.slug)}"><div class="project-heading"><span class="project-number">0${i+1}</span><div><h3><a href="/work/${e(p.slug)}/">${e(p.name)}</a></h3><span class="category">${e(p.type)}${p.year?` / ${e(p.year)}`:''}</span></div><a class="project-link" href="/work/${e(p.slug)}/" aria-label="Read about ${e(p.name)}">↗</a></div><a class="project-stage" style="--project-color:${e(p.color)}" href="/work/${e(p.slug)}/" aria-label="Read about ${e(p.name)}"><span class="stage-plus" aria-hidden="true">${i===0?'⟶':'+'}</span><span class="stage-inner">${["sap-erp","xacbank-chatbot","bachelors-project"].includes(p.slug)?`<img class="project-reveal-image" src="/assets/${e(p.slug)}-art.svg" alt="" aria-hidden="true">`:""}<span class="stage-word">${e(p.name)}</span></span><span class="stage-label">${["sap-erp","xacbank-chatbot","bachelors-project"].includes(p.slug)?"ILLUSTRATIVE ARTWORK · MOVE OR TAP TO REVEAL":"PROJECT IMAGERY TO COME"}</span></a><div class="project-description">${p.slug==='uulzy'&&p.role?`<div class="project-role"><span>ROLE</span><strong>${e(p.role)}</strong></div>`:''}<p>${e(p.description)}${p.url?` <a href="${e(p.url)}">Visit website ↗</a>`:''}</p>${p.missing?`<p class="missing">${e(p.missing)}</p>`:""}</div></article>`).join('');
 const timeline=document.querySelector('#timeline');if(timeline)timeline.innerHTML=data.experience.map((x,i)=>`<article class="timeline-row reveal"><span class="date">${e(x.date)}</span><div><h3>${e(x.company)}</h3><span class="role">${e(x.role)}</span><div class="experience-chips">${[['C#','.NET','SQL','SAP HANA','REST APIs','SAP Fiori','JavaScript'],['Copilot Studio','Power Automate','Microsoft Teams'],['Excel',window.portfolioLanguage==='mn'?'Зээлийн бүртгэл':'Loan records',window.portfolioLanguage==='mn'?'Хүүгийн тооцоолол':'Interest calculations']][i].map(skill=>`<span>${e(skill)}</span>`).join('')}</div></div><p>${e(x.description)}</p><svg class="experience-icon" viewBox="0 0 48 48" aria-hidden="true"><path d="${['M8 17L24 8l16 9-16 9zM8 25l16 9 16-9M8 33l16 9 16-9','M8 10h32v23H25l-10 8v-8H8zM15 18h18M15 25h12','M12 38V27M24 38V18M36 38V8'][i]}"/></svg></article>`).join('');
 const education=document.querySelector('#education');if(education)education.innerHTML=`<span class="section-label education-label">${window.portfolioLanguage==='mn'?'Боловсрол.':'Education.'}</span><div><h3>${e(data.education.institution)}</h3><p>${e(data.education.degree)}</p></div><p>${e(data.education.date)} <span class="degree-chip">BSc</span></p>`;
 const capabilities=document.querySelector('#capabilities');if(capabilities)capabilities.innerHTML=Object.entries(data.capabilities).map(([name,items],i)=>`<div><h3><svg class="skill-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${['M4 6c0-4 16-4 16 0s-16 4-16 0zm0 0v12c0 4 16 4 16 0V6M4 12c0 4 16 4 16 0','M8 5l-6 7 6 7M16 5l6 7-6 7M14 3l-4 18','M12 3v3M12 18v3M3 12h3M18 12h3M6 6l2 2M16 16l2 2M6 18l2-2M16 8l2-2M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10'][i%3]}"/></svg>${e(name)}</h3><ul>${items.flatMap(x=>x.split(' · ')).map(x=>`<li>${e(x)}</li>`).join('')}</ul>${name==='Exploring'?'<p>Areas I’m developing, rather than professional expertise.</p>':''}</div>`).join('');
 const skillsSection=document.querySelector('.hero');if(skillsSection){const banner=document.createElement('div');banner.className='skills-lights';banner.setAttribute('aria-label',window.portfolioLanguage==='mn'?'Техникийн ур чадвар':'Technical skills');const items=Object.values(data.capabilities).flat().join(' / ')+' / ';const track=document.createElement('div');track.className='skills-light-track';for(let i=0;i<2;i++){const copy=document.createElement('span');copy.textContent=items;if(i)copy.setAttribute('aria-hidden','true');track.append(copy);}banner.append(track);skillsSection.querySelector('.hero-rule').replaceWith(banner);}
 const cv=document.querySelector('#cv-state');if(cv&&data.cv.available)cv.innerHTML=`<a href="${e(data.cv.path)}" download>Download CV ↓</a>`;
 const detail=document.querySelector('#project-detail');if(detail){const p=data.projects.find(x=>x.slug===detail.dataset.slug);if(p){document.title=`${p.name} — Davaa`;detail.innerHTML=`<a href="/#work">← Selected work</a><p class="section-label">${e(p.type)}${p.year?` / ${e(p.year)}`:""}</p><h1>${e(p.name)}</h1><p class="detail-intro">${e(p.description)}</p>${p.role?`<div class="detail-role"><span class="section-label">ROLE</span><p>${e(p.role)}</p></div>`:""}<div class="project-stage" style="--project-color:${e(p.color)}"><span class="stage-inner"><span class="stage-word">${e(p.name)}</span></span><span class="stage-label">PROJECT IMAGERY TO COME</span></div>${p.context?`<div class="detail-grid">${['context','problem','solution','role'].map(k=>`<section><h2>${k==='role'?'My role':k.charAt(0).toUpperCase()+k.slice(1)}</h2><p>${e(p[k])}</p></section>`).join('')}</div>`:''}${p.url?`<p><a href="${e(p.url)}">Visit ${e(p.name)} ↗</a></p>`:''}<p class="detail-note">${e(p.missing)}</p>`;}}
 if(window.applyPortfolioLanguage)window.applyPortfolioLanguage();
 document.querySelectorAll('#projects .project').forEach((project,i)=>{const heading=project.querySelector('.project-heading'),description=project.querySelector('.project-description'),stage=project.querySelector('.project-stage');const copy=document.createElement('div');copy.className='project-copy';heading.before(copy);copy.append(heading,description);const chips=document.createElement('div');chips.className='project-chips';const skills=[['C#','.NET','SQL','SAP HANA','REST APIs','SAP Fiori'],['Copilot Studio','Power Automate','Microsoft Teams'],[]][i];chips.innerHTML=skills.map(x=>`<span>${e(x)}</span>`).join('');copy.append(chips);const link=document.createElement('a');link.className='project-view';link.href=stage.getAttribute('href');link.textContent=window.portfolioLanguage==='mn'?'Төслийг үзэх ↗':'View project ↗';copy.append(link);});
 const trainingTitle=document.querySelector('#training>.section-title');if(trainingTitle)trainingTitle.innerHTML=window.portfolioLanguage==='mn'?'Танхимаас гадуур<br><em>суралцах.</em>':'Learning beyond<br><em>the classroom.</em>';
 const training=document.querySelector('.resume-training');if(training){const mn=window.portfolioLanguage==='mn';const cards=[{label:mn?'Соёлын солилцоо':'Cultural exchange',title:mn?'Spirit Cultural Exchange — Ажиллах, аялах хөтөлбөр':'Spirit Cultural Exchange Work and Travel',body:mn?'Олон улсын ажиллах, аялах хөтөлбөр.':'An international work and travel program.',meta:'2024',icon:'M3 12l7-2 4-7 3 1-3 8 6 3-1 3-7-2-3 5-2-1 1-5-5-1z'},{label:mn?'Сургалт ба судалгаа':'Academic program',title:mn?'Японы шинэчлэл ба хөгжлийн судалгаа':'Study on the Modernization and Development of Japan',body:mn?'Японы шинэчлэл, хөгжлийн тухай МУИС болон JICA-ийн сургалт.':'A program from NUM and JICA exploring Japan’s modernization and development.',meta:'NUM & JICA · 2024',icon:'M3 5c4-2 7-2 9 0 2-2 5-2 9 0v15c-4-2-7-2-9 0-2-2-5-2-9 0zM12 5v15M6 9h3M15 9h3M6 13h3M15 13h3'},{label:mn?'Хэл ба ур чадвар':'Language & skills',title:mn?'Англи хэл: Дундаас дээш түвшин':'English: Upper-intermediate',body:mn?'Хамтран ажиллах, цагийг зохицуулах, бие даан суралцах ур чадвар.':'Communication, collaboration, and a commitment to continued learning.',meta:'',icon:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20M2 12h20M12 2c-6 6-6 14 0 20 6-6 6-14 0-20'}];training.innerHTML=cards.map((c,i)=>`<article class="learning-card"><div class="learning-label"><span>0${i+1}</span>${e(c.label)}</div><svg class="learning-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${c.icon}"/></svg><h3>${e(c.title)}</h3><p>${e(c.body)}</p>${i===2?`<div class="learning-chips">${(mn?['Багаар ажиллах','Цагийн менежмент','Бие даан суралцах']:['Teamwork','Time management','Independent learning']).map(x=>`<span>${e(x)}</span>`).join('')}</div>`:`<div class="learning-meta">${e(c.meta)}</div>`}<div class="learning-art" aria-hidden="true"><span></span><span></span></div></article>`).join('');}
 const experienceTitle=document.querySelector('#experience>.section-title');if(experienceTitle){experienceTitle.textContent=window.portfolioLanguage==='mn'?'Туршлага.':'Experience.';const subtitle=document.createElement('p');subtitle.className='experience-subtitle';subtitle.textContent=window.portfolioLanguage==='mn'?'Санааг хэрэгцээтэй систем болгох.':'Turning ideas into useful systems.';experienceTitle.after(subtitle);}
 document.querySelectorAll('.about-copy article').forEach((card,i)=>{const ornament=document.createElement('div');ornament.className='about-ornament';ornament.setAttribute('aria-hidden','true');ornament.innerHTML=i?'<svg viewBox="0 0 24 24"><path d="M14 2L5 14h6l-1 8 9-13h-6z"/></svg>':'<span></span><span></span>';card.append(ornament);});
 const marquee=document.querySelector('.motion-marquee');if(marquee){marquee.classList.add('skills-lights');const track=marquee.querySelector('div'),copy=document.createElement('span');copy.textContent=track.textContent+' — ';track.textContent='';track.className='skills-light-track';track.append(copy);const duplicate=copy.cloneNode(true);duplicate.setAttribute('aria-hidden','true');track.append(duplicate);}
 initMotion();
 initSkillEntrances();
}).catch(()=>{const target=document.querySelector('#projects');if(target)target.innerHTML='<p>Portfolio content could not load. <a href="/overview.html">Read the portfolio overview</a>.</p>';});
function initMotion(){renderVectorSymbols();initImageReveals();if(window.startPortfolioMotion)window.startPortfolioMotion();if(window.startParticleSphere)window.startParticleSphere();if(document.querySelector('#project-detail')&&window.gsap&&window.startAtmosphere){const stop=window.startAtmosphere(window.gsap);window.addEventListener('pagehide',stop,{once:true});}}
document.querySelectorAll('.play-letters button').forEach(button=>button.addEventListener('click',()=>{button.classList.toggle('active');button.setAttribute('aria-pressed',String(button.classList.contains('active')))}));

function initImageReveals(){
 document.querySelectorAll('.project-stage').forEach(stage=>{
  const inner=stage.querySelector('.stage-inner'),image=stage.querySelector('.project-reveal-image');if(!image)return;
  inner.classList.add('has-image-reveal');let touchReveal=false;
  const reveal=event=>{const r=inner.getBoundingClientRect();inner.style.setProperty('--reveal-x',`${event.clientX-r.left}px`);inner.style.setProperty('--reveal-y',`${event.clientY-r.top}px`);inner.style.setProperty('--reveal-radius',`${Math.min(170,r.width*.3)}px`);inner.classList.add('is-revealing');};
  stage.addEventListener('pointermove',event=>{if(event.pointerType!=='touch')reveal(event);},{passive:true});
  stage.addEventListener('pointerleave',()=>{if(touchReveal)return;inner.style.setProperty('--reveal-radius','0px');inner.classList.remove('is-revealing');});
  stage.addEventListener('pointerdown',event=>{if(event.pointerType==='touch'){reveal(event);touchReveal=true;}});
  stage.addEventListener('click',event=>{if(touchReveal&&!stage.dataset.touchReady){event.preventDefault();stage.dataset.touchReady='true';}});
  stage.addEventListener('focus',()=>{inner.style.setProperty('--reveal-x','50%');inner.style.setProperty('--reveal-y','50%');inner.style.setProperty('--reveal-radius','160px');inner.classList.add('is-revealing');});
  stage.addEventListener('blur',()=>{touchReveal=false;delete stage.dataset.touchReady;inner.style.setProperty('--reveal-radius','0px');inner.classList.remove('is-revealing');});
 });
}

/* Draw decorative symbols as vectors so mobile fonts cannot turn them into emoji. */
function renderVectorSymbols(){
 const paths={'↗':'M5 19L19 5M5 5h14v14','↘':'M5 5l14 14M5 19h14V5','↑':'M12 21V3M5 10l7-7 7 7','←':'M21 12H3M10 5l-7 7 7 7','→':'M3 12h18M14 5l7 7-7 7','⟶':'M2 12h20M16 6l6 6-6 6','✳':'M12 2v20M2 12h20M5 5l14 14M5 19L19 5','◌':'M12 3a9 9 0 1 0 0 18a9 9 0 1 0 0-18'};
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 for(const node of nodes){if(node.parentElement.closest('script,style,svg'))continue;if(!/[↗↘↑←→⟶✳◌]/.test(node.textContent))continue;const fragment=document.createDocumentFragment();for(const part of node.textContent.split(/([↗↘↑←→⟶✳◌])/)){if(!paths[part]){fragment.append(document.createTextNode(part));continue;}const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.setAttribute('class','symbol-icon');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',paths[part]);svg.append(path);fragment.append(svg);}node.replaceWith(fragment);}
}

document.querySelector('.print-resume')?.addEventListener('click',()=>window.print());
const themeButton=document.createElement('button');themeButton.className='theme-switch';themeButton.type='button';themeButton.innerHTML='<svg class="theme-sun" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/></svg><svg class="theme-moon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15.5A8.5 8.5 0 0 1 8.5 4a8.5 8.5 0 1 0 11.5 11.5Z"/></svg>';const setTheme=dark=>{document.documentElement.dataset.theme=dark?'dark':'light';themeButton.setAttribute('aria-pressed',String(dark));themeButton.setAttribute('aria-label',window.portfolioLanguage==='mn'?'Өнгөний горим солих':'Switch color theme');try{localStorage.setItem('portfolio-theme',dark?'dark':'light');}catch{}};let savedTheme;try{savedTheme=localStorage.getItem('portfolio-theme');}catch{}setTheme(savedTheme==='dark');themeButton.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme!=='dark'));document.querySelector('.nav')?.append(themeButton);

function initSkillEntrances(){
 if(!('IntersectionObserver' in window))return;
 const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;entry.target.querySelectorAll('li').forEach((chip,i)=>{chip.style.setProperty('--chip-delay',`${i*55}ms`);chip.classList.add('chip-enter');});observer.unobserve(entry.target);}}, {threshold:.15});
 document.querySelectorAll('.capability-grid>div').forEach(group=>observer.observe(group));
}
