const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fetch('/data/portfolio.json').then(r => {if(!r.ok) throw new Error('Content unavailable'); return r.json()}).then(data => {
 const e=escapeHTML;
 const email=document.querySelector("#email");if(email){email.href="mailto:"+data.contact.email;email.textContent=data.contact.email+" ↗";}
 const location=document.querySelector("#location");if(location)location.textContent=data.contact.location;
 const projects=document.querySelector('#projects');
 if(projects) projects.innerHTML=data.projects.map((p,i)=>`<article class="project reveal"><div class="project-heading"><span class="project-number">0${i+1}</span><div><h3><a href="/work/${e(p.slug)}/">${e(p.name)}</a></h3><span class="category">${e(p.type)}</span></div><a class="project-link" href="/work/${e(p.slug)}/" aria-label="Read about ${e(p.name)}">↗</a></div><a class="project-stage" style="--project-color:${e(p.color)}" href="/work/${e(p.slug)}/" aria-label="Read about ${e(p.name)}"><span class="stage-plus" aria-hidden="true">+</span><span class="stage-word">${['UULZY','GERTE<br><em>LIFE</em>','Help,<br><em>in Teams.</em>','System<br><em>studies.</em>'][i]}</span><span class="stage-label">TYPOGRAPHIC PLACEHOLDER / PROJECT IMAGERY TO COME</span></a><div class="project-description"><p>${e(p.description)}${p.url?` <a href="${e(p.url)}">Visit website ↗</a>`:''}</p><p class="missing">${e(p.missing)}</p></div></article>`).join('');
 const timeline=document.querySelector('#timeline');if(timeline)timeline.innerHTML=data.experience.map(x=>`<article class="timeline-row reveal"><span class="date">${e(x.date)}</span><div><h3>${e(x.company)}</h3><span class="role">${e(x.role)}</span></div><p>${e(x.description)}</p></article>`).join('');
 const education=document.querySelector('#education');if(education)education.innerHTML=`<span class="section-label">EDUCATION</span><div><h3>${e(data.education.institution)}</h3><p>${e(data.education.degree)}</p></div><p>${e(data.education.date)}</p>`;
 const capabilities=document.querySelector('#capabilities');if(capabilities)capabilities.innerHTML=Object.entries(data.capabilities).map(([name,items])=>`<div><h3>${e(name)}</h3><ul>${items.map(x=>`<li>${e(x)}</li>`).join('')}</ul>${name==='Exploring'?'<p>Areas I’m developing, rather than professional expertise.</p>':''}</div>`).join('');
 const cv=document.querySelector('#cv-state');if(cv&&data.cv.available)cv.innerHTML=`<a href="${e(data.cv.path)}" download>Download CV ↓</a>`;
 const detail=document.querySelector('#project-detail');if(detail){const p=data.projects.find(x=>x.slug===detail.dataset.slug);if(p){document.title=`${p.name} — Davaa`;detail.innerHTML=`<a href="/#work">← Selected work</a><p class="section-label">${e(p.type)}</p><h1>${e(p.name)}</h1><p>${e(p.description)}</p><div class="project-stage" style="--project-color:${e(p.color)}"><span class="stage-word">${e(p.name)}</span><span class="stage-label">PROJECT IMAGERY TO COME</span></div>${p.context?`<div class="detail-grid">${['context','problem','solution','role'].map(k=>`<section><h2>${k==='role'?'My role':k.charAt(0).toUpperCase()+k.slice(1)}</h2><p>${e(p[k])}</p></section>`).join('')}</div>`:''}${p.url?`<p><a href="${e(p.url)}">Visit ${e(p.name)} ↗</a></p>`:''}<p class="detail-note">${e(p.missing)} This page will develop into a fuller case study as supporting material is added.</p>`;}}
 initMotion();
}).catch(()=>{const target=document.querySelector('#projects');if(target)target.innerHTML='<p>Portfolio content could not load. <a href="/overview.html">Read the portfolio overview</a>.</p>';});
function initMotion(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{entry.target.classList.toggle('in-view',entry.isIntersecting)}),{threshold:.12});document.querySelectorAll('.reveal,.transition,.contact').forEach(el=>observer.observe(el));document.body.classList.add('motion-ready');let queued=false;addEventListener('scroll',()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{const hero=document.querySelector('.hero-name');if(hero)hero.style.setProperty('--hero-shift',Math.min(scrollY*.045,35));queued=false})},{passive:true});}
document.querySelectorAll('.play-letters button').forEach(button=>button.addEventListener('click',()=>{button.classList.toggle('active');button.setAttribute('aria-pressed',String(button.classList.contains('active')))}));
